<section class="mt-3 card card-body">
    <h1 class="">Gerenciar Usuários</h1>

    <div class="mt-2">
        <a href="/usuarios/novo" class="btn btn-outline-dark">Novo Usuario</a>
        <!-- <a href="/alunos/relatorio" target="_blank" class="btn btn-outline-dark">Gerar PDF</a> -->
    </div>

    <table class="table table-striped table-hover mt-4 text-center">
        <thead class="table-dark">
            <tr>
                <th>ID</th>
                <th>Nome</th>
                <th>Email</th>

                <th>Perfil</th>
                <th>Ações</th>
            </tr>
        </thead>

        <tbody>
            <?php
            foreach ($users ?? [] as $user) {
                echo "
                    <tr>
                        <td>{$user->id}</td>
                        <td>{$user->nome}</td>
                        <td>{$user->email}</td>
                        
                        <td>{$user->perfil}</td>
                        <td> 
                            <a href='/usuarios/editar?id={$user->id}' class='btn btn-warning'>Editar</a>
                            <a href='/usuarios/excluir?id={$user->id}' class='btn btn-danger'>Excluir</a>
                        </td>
                        
                    </tr>
                ";
            }
            ?>
        </tbody>
    </table>
</section>