<section class="mt-3 card card-body">
    <h1>Nova Categoria</h1>

    <div class="row">
        <div class="col">
            <form action="" method="POST">
                <label for="nome">Nome</label>
                <input name="nome" type="text" id="nome" class="form-control mb-3">

                <label for="vagas">Vagas</label>
                <input name="vagas" type="text" id="vagas" class="form-control mb-3">

                <label for="localidade">Localidade</label>
                <!-- <input name="localidade" type="text" id="localidade" class="form-control mb-3"> -->
                <select name="localidade" type="text" id="localidade" class="form-control mb-3">
                    <Option>Selecione</Option>
                    <Option>Aldeota</Option>
                    <Option>Washington Soares</Option>
                </select>

                <button class="btn btn-primary">Cadastrar</button>

            </form>
        </div>
    </div>
</section>