
<section class="mt-3 card card-body">
    <h1>Editar Aluno</h1>

    <div class="row">
        <div class="col">
            <form action="" method="POST">
                <label for="nome">Nome</label>
                <input name="nome" type="text" id="nome" class="form-control mb-3" value="<?php echo $dados[0]->nome; ?>">

                <label for="endereco">Endereço</label>
                <input name="endereco" type="text" id="email" class="form-control mb-3" value="<?php echo $dados[0]->endereco; ?>">

                <label for="formacao">Formação</label>
                <input name="formacao" type="text" id="formacao" class="form-control mb-3" value="<?php echo $dados[0]->formacao; ?>">

                <label for="cpf">CPF</label>
                <input name="cpf" type="text" id="cpf" class="form-control mb-3" value="<?php echo $dados[0]->cpf; ?>">

                <button class="btn btn-primary">Editar</button>

            </form>
        </div>
    </div>
</section>