<section class="mt-3 card card-body">
    <h1 class="">Gerenciar Professores</h1>

    <div class="mt-2">
        <a href="/professores/novo" class="btn btn-outline-dark">Novo Professor</a>
        <a href="/professores/relatorio" class="btn btn-outline-dark">Gerar PDF</a>
    </div>

    <table class="table table-striped table-hover mt-4 text-center">
        <thead class="table-dark">
            <tr>
                <th>#ID</th>
                <th>Nome</th>
                <th>Endereço</th>
                <th>Formação</th>
                <th>Status</th>
                <th>CPF</th>
                <th>Ações</th>
            </tr>
        </thead>

        <tbody>
            <?php
            foreach ($professores ?? [] as $professor) {
                echo "
                    <tr>
                        <td>{$professor->id}</td>
                        <td>{$professor->nome}</td>
                        <td>{$professor->endereco}</td>
                        <td>{$professor->formacao}</td>
                        <td>{$professor->status}</td>
                        <td>{$professor->cpf}</td>
                        <td> 
                            <a href='/professores/editar?id={$professor->id}' class='btn btn-warning'>Editar</a>
                            <a href='/professores/excluir?id={$professor->id}' class='btn btn-danger'>Excluir</a>
                        </td>
                        
                    </tr>
                ";
            }
            ?>
        </tbody>
    </table>
</section>