<section class="mt-3 card card-body">
    <h1>Novo Curso</h1>

    <div class="row">
        <div class="col">
            <form action="" method="POST">
                <label for="nome">Nome</label>
                <input name="nome" type="text" id="nome" class="form-control mb-3">

                <label for="horario">Carga Horaria</label>
                <input name="horario" type="text" id="horario" class="form-control mb-3">

                <label for="descricao">Descrição</label>
                <!-- <input name="descricao" type="text" id="descricao" class="form-control mb-3"> -->
                <select name="descricao" type="text"  id="descricao" class="form-control mb-3">
                    <Option>Selecione</Option>
                    <Option>Profissionalizante</Option>
                    <Option>Técnico</Option>
                    <Option>Graduação</Option>
                </select>

                <button class="btn btn-primary">Cadastrar</button>

            </form>
        </div>
    </div>
</section>