<?php
    $curso = $dados[0];
?>
<section class="mt-3 card card-body">
    <h1>Editar Curso</h1>

    <div class="row">
        <div class="col">
            <form action="" method="POST">
                <label for="nome">Nome</label>
                <input name="nome" type="text" id="nome" class="form-control mb-3" value="<?php echo $curso->nome; ?>">

                <label for="horario">Carga Horaria</label>
                <input name="horario" type="text" id="horario" class="form-control mb-3" value="<?php echo $curso->cargaHoraria; ?>">

                <label for="descricao">Descrição</label>
                <input name="descricao" type="text" id="descricao" class="form-control mb-3" value="<?php echo $curso->descricao; ?>">

                <button class="btn btn-primary">Editar</button>

            </form>
        </div>
    </div>
</section>