<section class="mt-3 card card-body">
    <h1 class="">Gerenciar Cursos</h1>

    <div class="mt-2">
        <a href="/cursos/novo" class="btn btn-outline-dark">Novo Curso</a>
        <a href="/cursos/relatorio" class="btn btn-outline-dark">Gerar PDF</a>
    </div>

    <table class="table table-striped table-hover mt-4 text-center">
        <thead class="table-dark">
            <tr>
                <th>ID</th>
                <th>Nome</th>
                <th>Carga Horaria</th>
                <th>Descrição</th>
                <th>Status</th>
                <th>Ações</th>
            </tr>
        </thead>

        <tbody>
            <?php
                foreach ($cursos ?? [] as $curso) {
                    echo "
                        <tr>
                            <td>{$curso->id}</td>
                            <td>{$curso->nome}</td>
                            <td>{$curso->cargaHoraria}</td>
                            <td>{$curso->descricao}</td>
                            <td>{$curso->status}</td>
                            <td> 
                                <a href='/cursos/editar?id={$curso->id}' class='btn btn-warning'>Editar</a>
                                <a href='/cursos/excluir?id={$curso->id}' class='btn btn-danger'>Excluir</a>
                            </td>

                        </tr>

                    ";
                }
            ?>
        </tbody>
    </table>
</section>