<section class="mt-3 card card-body">
    <h1 class="">Gerenciar Cursos</h1>

    <div class="mt-2">
        <a href="/alunos/novo" class="btn btn-outline-dark">Novo Curso</a>
    </div>

    <table class="table table-striped table-hover mt-4">
        <thead class="table-dark">
            <tr>
                <th>Nome</th>
                <th>Carga Horaria</th>
                <th>Status</th>
                <th>Descrição</th>
                <th>Ações</th>
            </tr>
        </thead>

        <tbody>

        </tbody>
    </table>
</section>